CREATE TABLE HABIT_EVENT (
	UUID_ID VARCHAR(46),
	HABIT_UUID VARCHAR(46),
	CREATED_AT timestamp,
	EVENT_YEAR int,
	WEEK_NB int,
	PRIMARY KEY(UUID_ID),
	FOREIGN KEY (HABIT_UUID) REFERENCES HABIT(UUID_ID)
);